### ISSUE TITLE
Alduin Settings

### ISSUE THREAD

**Issue by AlessandroYorba** [RobinThrift/Dotfiles#4]
Yo! Stoked you're using Alduin. ; ) Let me save you a few bytes in your .vimrc. 
If you update or clone to the latest commit for Alduin you can remove `let g:alduin_Shout_Windhelm = 1`  The light red color is now the default for the `Special`.  Thanks

**Comment by RobinThrift** [comment]
Thanks for the info. That's great to hear, I absolutely love your colourscheme! I'll update my plugins and push the new dotfiles soon then. Thanks a lot!

**Comment by AlessandroYorba** [comment]
Cool!!

**Comment by RobinThrift** [comment]
Upaded, thanks a lot!
